export const API_REQUEST = 'API_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE';
export const LOGIN_POPUP_CLOSE = 'LOGIN_POPUP_CLOSE';
export const LOGIN_POPUP_OPEN = 'LOGIN_POPUP_OPEN';
export const SET_LOADING= 'SET_LOADING';
export const SEARCH_USER_ITEM_REQUEST = 'SEARCH_USER_ITEM_REQUEST';
export const SEARCH_USER_ITEM_SUCCESS = 'SEARCH_USER_ITEM_SUCCESS';
export const SEARCH_USER_ITEM_FAILURE = 'SEARCH_USER_ITEM_FAILURE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const SEARCH_USER_CLOTHES_REQUEST = 'SEARCH_USER_CLOTHES_REQUEST';
export const SEARCH_USER_CLOTHES_SUCCESS = 'SEARCH_USER_CLOTHES_SUCCESS';
export const SEARCH_USER_CLOTHES_FAILURE = 'SEARCH_USER_CLOTHES_FAILURE';

export const CREATE_USER_ITEM_REQUEST = 'CREATE_USER_ITEM_REQUEST';
export const CREATE_USER_ITEM_SUCCESS = 'CREATE_USER_ITEM_SUCCESS';
export const CREATE_USER_ITEM_FAILURE = 'CREATE_USER_ITEM_FAILURE';

export const UPDATE_USER_ITEM_REQUEST = 'UPDATE_USER_ITEM_REQUEST';
export const UPDATE_USER_ITEM_SUCCESS = 'UPDATE_USER_ITEM_SUCCESS';
export const UPDATE_USER_ITEM_FAILURE = 'UPDATE_USER_ITEM_FAILURE';

export const DELETE_USER_ITEM_REQUEST = 'DELETE_USER_ITEM_REQUEST';
export const DELETE_USER_ITEM_SUCCESS = 'DELETE_USER_ITEM_SUCCESS';
export const DELETE_USER_ITEM_FAILURE = 'DELETE_USER_ITEM_FAILURE';

export const GET_USER_ITEMS_REQUEST = 'GET_USER_ITEMS_REQUEST';
export const GET_USER_ITEMS_SUCCESS = 'GET_USER_ITEMS_SUCCESS';
export const GET_USER_ITEMS_FAILURE = 'GET_USER_ITEMS_FAILURE';

export const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST';
export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
export const GET_ALL_ITEMS_FAILURE = 'GET_ALL_ITEMS_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';

export const UPLOAD_ITEM_IMAGE_REQUEST = 'UPLOAD_ITEM_IMAGE_REQUEST';
export const UPLOAD_ITEM_IMAGE_SUCCESS = 'UPLOAD_ITEM_IMAGE_SUCCESS';
export const UPLOAD_ITEM_IMAGE_FAILURE = 'UPLOAD_ITEM_IMAGE_FAILURE';

export const GET_USER_CLOTHES_REQUEST = 'GET_USER_CLOTHES_REQUEST';
export const GET_USER_CLOTHES_SUCCESS = 'GET_USER_CLOTHES_SUCCESS';
export const GET_USER_CLOTHES_FAILURE = 'GET_USER_CLOTHES_FAILURE';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

export const GET_ITEM_IMAGE_REQUEST = 'GET_ITEM_IMAGE_REQUEST';
export const GET_ITEM_IMAGE_SUCCESS = 'GET_ITEM_IMAGE_SUCCESS';
export const GET_ITEM_IMAGE_FAILURE = 'GET_ITEM_IMAGE_FAILURE';