export const API_REQUEST = 'API_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE';
export const LOGIN_POPUP_CLOSE = 'LOGIN_POPUP_CLOSE';
export const LOGIN_POPUP_OPEN = 'LOGIN_POPUP_OPEN';
export const SET_LOADING= 'SET_LOADING';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';


// Search User Item
export const SEARCH_USER_ITEM_REQUEST = 'SEARCH_USER_ITEM_REQUEST';
export const SEARCH_USER_ITEM_SUCCESS = 'SEARCH_USER_ITEM_SUCCESS';
export const SEARCH_USER_ITEM_FAILURE = 'SEARCH_USER_ITEM_FAILURE';

// Search All Clothing Items
export const SEARCH_ALL_CLOTHING_ITEMS_REQUEST = 'SEARCH_ALL_CLOTHING_ITEMS_REQUEST';
export const SEARCH_ALL_CLOTHING_ITEMS_SUCCESS = 'SEARCH_ALL_CLOTHING_ITEMS_SUCCESS';
export const SEARCH_ALL_CLOTHING_ITEMS_FAILURE = 'SEARCH_ALL_CLOTHING_ITEMS_FAILURE';


// Clothing Items
export const CREATE_CLOTHING_ITEM_REQUEST = 'CREATE_CLOTHING_ITEM_REQUEST';
export const CREATE_CLOTHING_ITEM_SUCCESS = 'CREATE_CLOTHING_ITEM_SUCCESS';
export const CREATE_CLOTHING_ITEM_FAILURE = 'CREATE_CLOTHING_ITEM_FAILURE';

export const UPDATE_CLOTHING_ITEM_REQUEST = 'UPDATE_CLOTHING_ITEM_REQUEST';
export const UPDATE_CLOTHING_ITEM_SUCCESS = 'UPDATE_CLOTHING_ITEM_SUCCESS';
export const UPDATE_CLOTHING_ITEM_FAILURE = 'UPDATE_CLOTHING_ITEM_FAILURE';

export const DELETE_CLOTHING_ITEM_REQUEST = 'DELETE_CLOTHING_ITEM_REQUEST';
export const DELETE_CLOTHING_ITEM_SUCCESS = 'DELETE_CLOTHING_ITEM_SUCCESS';
export const DELETE_CLOTHING_ITEM_FAILURE = 'DELETE_CLOTHING_ITEM_FAILURE';

export const GET_CLOTHING_ITEM_REQUEST = 'GET_CLOTHING_ITEM_REQUEST';
export const GET_CLOTHING_ITEM_SUCCESS = 'GET_CLOTHING_ITEM_SUCCESS';
export const GET_CLOTHING_ITEM_FAILURE = 'GET_CLOTHING_ITEM_FAILURE';

export const GET_USER_CLOTHING_ITEMS_REQUEST = 'GET_USER_CLOTHING_ITEMS_REQUEST';
export const GET_USER_CLOTHING_ITEMS_SUCCESS = 'GET_USER_CLOTHING_ITEMS_SUCCESS';
export const GET_USER_CLOTHING_ITEMS_FAILURE = 'GET_USER_CLOTHING_ITEMS_FAILURE';

export const GET_ALL_CLOTHING_ITEMS_REQUEST = 'GET_ALL_CLOTHING_ITEMS_REQUEST';
export const GET_ALL_CLOTHING_ITEMS_SUCCESS = 'GET_ALL_CLOTHING_ITEMS_SUCCESS';
export const GET_ALL_CLOTHING_ITEMS_FAILURE = 'GET_ALL_CLOTHING_ITEMS_FAILURE';

// Trade Actions
export const REQUEST_TRADE_REQUEST = 'REQUEST_TRADE_REQUEST';
export const REQUEST_TRADE_SUCCESS = 'REQUEST_TRADE_SUCCESS';
export const REQUEST_TRADE_FAILURE = 'REQUEST_TRADE_FAILURE';

export const GET_USER_SENT_TRADES_REQUEST = 'GET_USER_SENT_TRADES_REQUEST';
export const GET_USER_SENT_TRADES_SUCCESS = 'GET_USER_SENT_TRADES_SUCCESS';
export const GET_USER_SENT_TRADES_FAILURE = 'GET_USER_SENT_TRADES_FAILURE';

export const GET_USER_RECEIVED_TRADES_REQUEST = 'GET_USER_RECEIVED_TRADES_REQUEST';
export const GET_USER_RECEIVED_TRADES_SUCCESS = 'GET_USER_RECEIVED_TRADES_SUCCESS';
export const GET_USER_RECEIVED_TRADES_FAILURE = 'GET_USER_RECEIVED_TRADES_FAILURE';

export const GET_TRADE_REQUEST = 'GET_TRADE_REQUEST';
export const GET_TRADE_SUCCESS = 'GET_TRADE_SUCCESS';
export const GET_TRADE_FAILURE = 'GET_TRADE_FAILURE';

export const ACCEPT_OR_DECLINE_TRADE_REQUEST = 'ACCEPT_OR_DECLINE_TRADE_REQUEST';
export const ACCEPT_OR_DECLINE_TRADE_SUCCESS = 'ACCEPT_OR_DECLINE_TRADE_SUCCESS';
export const ACCEPT_OR_DECLINE_TRADE_FAILURE = 'ACCEPT_OR_DECLINE_TRADE_FAILURE';

export const SET_USER_ID = 'SET_USER_ID';

